/* 제약조건 : 데이터의 무결성(정확하고 일관된 값)을 보장하기 위해 테이블에 설정되는 규칙
 * NOT NULL : 지정한 열에 값이 있어야 한다
 * UNIQUE : 값이 유일해야 한다, 단 NULL 허용
 * PRIMARY KEY(PK) : 유일해야 하며 NULL 을 허용하지 않음
 * FOREIGN KEY(FK) : 다른 테이블의 열을 참조하여 존재하는 값만 입력 할 수 있음
 * CHECK : 설정한 조건식을 만족하는 데이터만 입력 가능 */
CREATE TABLE TABLE_NOTNULL (
	LOGIN_ID VARCHAR2(20) NOT NULL,
	LOGIN_PWD VARCHAR2(20) NOT NULL,
	TEL VARCHAR2(20)
);

SELECT * FROM TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD, TEL)
	VALUES('홍길동', 'GILDONG123', NULL);
	
UPDATE TABLE_NOTNULL
	SET LOGIN_PWD = 'TEST12345678'
WHERE LOGIN_ID = '홍길동';

UPDATE TABLE_NOTNULL
	SET TEL = '010-4399-5385'
WHERE LOGIN_ID = '홍길동';

-- 이미 만들어진 테이블에 제약 조건 지정하기
ALTER TABLE TABLE_NOTNULL
	MODIFY TEL NOT NULL;
	
-- UNIQUE 제약 조건 : 중복 허용하지 않는 특성
CREATE TABLE TABLE_UNIQUE (
	LOGIN_ID VARCHAR2(20) UNIQUE,
	LOGIN_PWD VARCHAR2(20) NOT NULL,
	TEL VARCHAR2(20)
);

INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
	VALUES('홍길동', 'PASS1234', '010-1234-5678');
	
INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
	VALUES('홍길일', 'PASS1244', '010-4567-5678');
	
INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
	VALUES(NULL, 'PASS2020', '010-1344-5678');

SELECT * FROM TABLE_UNIQUE;

-- PRIMARY KEY - 유일하게 하나만 있는 값 : UNIQUE 특성과 NOT NULL 제약조건을 모두 가진다
-- PK 로 지정하면 자동으로 인덱스가 만들어짐 (PK 를 통한 검색속도 향상)
CREATE TABLE TABLE_PK (
	LOGIN_ID VARCHAR2(20) PRIMARY KEY,
	LOGIN_PWD VARCHAR2(20) NOT NULL,
	TEL VARCHAR2(20)
);

INSERT INTO TABLE_PK VALUES('홍길동', 'PASS1010', '010-1234-5678');
INSERT INTO TABLE_PK VALUES('홍길일', 'PASS1020', '010-2234-5678');
INSERT INTO TABLE_PK VALUES('홍길이', 'PASS1030', '010-3234-5678');

-- 다른 테이블과 관계를 맺는 FK
-- 서로다른 테이블간 관계를 정의하는 데 사용하는 제약 조건
-- 참조하고 있는 기본키의 데이터 타입과 일치해야 하며, 외래키에 참조되고 있는 기본키는 삭제불가능
CREATE TABLE DEPT_FK (
	DEPTNO NUMBER(2) PRIMARY KEY,
	DNAME VARCHAR2(14),
	LOC VARCHAR2(13)
);

CREATE TABLE EMP_FK (
	EMPNO NUMBER(4) PRIMARY KEY,
	ENAME VARCHAR2(10),
	JOB VARCHAR2(9),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7, 2),
	COMM NUMBER(7, 2),
	DEPTNO NUMBER(2) REFERENCES DEPT_FK (DEPTNO)
);
INSERT INTO DEPT_FK VALUES(10, '책사', 'SEOUL');
INSERT INTO EMP_FK VALUES (9001, '홍길동', '무사', 1001, SYSDATE, 9000, 1000, 10);
SELECT * FROM EMP_FK;
SELECT * FROM DEPT_FK;

DELETE FROM EMP_FK
WHERE DEPTNO = 10;

DELETE FROM DEPT_FK
WHERE DEPTNO = 10;

-- 데이터 형태와 범위를 정하는 CHECK
-- ID 및 PWD 등의 길이 제한
-- 유효 범위값 확인 등에 사용
CREATE TABLE TABLE_CHECK (
	LOGIN_ID VARCHAR2(20) PRIMARY KEY,
	LOGIN_PWD VARCHAR2(20) CHECK(LENGTH(LOGIN_PWD) > 6),
	TEL VARCHAR2(20)
);

INSERT INTO TABLE_CHECK VALUES ('민지', '1234567', '010-1234-5678');

-- 기본값을 정하는 DEFAULT : 특정 열에 저장 할 값을 지정하지 않는 경우 기본값을 지정
CREATE TABLE TABLE_DEFAULT (
	LOGIN_ID VARCHAR2(20) PRIMARY KEY,
	LOGIN_PWD VARCHAR2(20) DEFAULT '1234567',	-- 값에 NULL 값이 들어가면 자동으로 설정 된다
	TEL VARCHAR2(20)
);

INSERT INTO TABLE_DEFAULT VALUES ('민지', NULL, '010-1234-5678');
INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) VALUES ('민지', '000-0000-0000');

SELECT * FROM TABLE_DEFAULT;
