/* DML (Data Manipulation Language) : INSERT(입력), UPDATE(수정), DELETE(삭제) 
 * 연습용 테이블 생성하기 */
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

-- TABLE 에 데이터를 추가 하는 INSERT

-- 1. INSERT INTO TABLE_NAME(COLUMN_NAME1, COLUMN_NAME2, COLUMN_NAME2) VALUES(VALUE1, VALUE2, VALUE3)
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(50, 'DATABASE', 'SEOUL');

INSERT INTO DEPT_TEMP VALUES (60, 'BACKEND', 'BUSAN');	-- COLUMN의 순서에 맞게 데이터값이 입력 된다

INSERT INTO DEPT_TEMP(DEPTNO) VALUES(70);	-- COLUMN 하나만 지정해서 나머지는 NULL 값

INSERT INTO DEPT_TEMP VALUES (80, 'FRONTEND', 'INCHEON');

INSERT INTO DEPT_TEMP VALUES (90, NULL, 'INCHEON');
INSERT INTO DEPT_TEMP VALUES (95, ' ', 'INCHEON');